#![cfg(target_os = "macos")]

use anyhow::{anyhow, Result};
use core_graphics::event::{CGEvent, CGEventFlags, CGEventTapLocation, CGKeyCode};
use core_graphics::event_source::{CGEventSource, CGEventSourceStateID};
use objc2::msg_send;
use objc2::runtime::AnyObject;
use objc2_foundation::NSString;

const KEY_V: CGKeyCode = 9;
const NS_PASTEBOARD_TYPE_STRING: &str = "public.utf8-plain-text";
// nspasteboard.org convention — clipboard managers (FlyCut, Maccy, Pastebot,
// Raycast, Alfred, Paste, etc.) that honor it will skip recording entries
// declaring these types. We mark dictation output as transient + auto-generated
// + concealed so it pastes normally but doesn't pollute clipboard history.
const NS_PASTEBOARD_TYPE_TRANSIENT: &str = "org.nspasteboard.TransientType";
const NS_PASTEBOARD_TYPE_AUTOGENERATED: &str = "org.nspasteboard.AutoGeneratedType";
const NS_PASTEBOARD_TYPE_CONCEALED: &str = "org.nspasteboard.ConcealedType";
const NS_APPLICATION_ACTIVATE_ALL_WINDOWS: u64 = 1 << 1;

#[derive(Clone)]
pub struct FocusTarget {
    pub pid: i32,
}

pub fn capture_frontmost() -> Option<FocusTarget> {
    unsafe {
        let cls = objc2::class!(NSWorkspace);
        let ws: *mut AnyObject = msg_send![cls, sharedWorkspace];
        if ws.is_null() {
            return None;
        }
        let app: *mut AnyObject = msg_send![ws, frontmostApplication];
        if app.is_null() {
            return None;
        }
        let pid: i32 = msg_send![app, processIdentifier];
        Some(FocusTarget { pid })
    }
}

pub fn paste_text(text: &str, target: Option<FocusTarget>) -> Result<()> {
    let prev = read_pasteboard();
    log::debug!("paste_text: saved previous clipboard ({} chars)", prev.as_ref().map_or(0, |s| s.len()));
    write_pasteboard(text)?;
    log::debug!("paste_text: wrote {} chars to pasteboard", text.len());
    if let Some(t) = target {
        restore_focus(&t)?;
        log::debug!("paste_text: restored focus, waiting 60ms");
        std::thread::sleep(std::time::Duration::from_millis(60));
    }
    synthesize_cmd_v()?;
    log::debug!("paste_text: synthesized Cmd+V, waiting 150ms before restore");
    std::thread::sleep(std::time::Duration::from_millis(150));
    let result = match prev {
        Some(s) => {
            log::debug!("paste_text: restoring previous clipboard ({} chars)", s.len());
            write_pasteboard_plain(&s)
        }
        None => {
            log::debug!("paste_text: clearing clipboard (no previous content)");
            clear_pasteboard()
        }
    };
    log::debug!("paste_text: done");
    result
}

fn write_pasteboard(text: &str) -> Result<()> {
    unsafe {
        let cls = objc2::class!(NSPasteboard);
        let pb: *mut AnyObject = msg_send![cls, generalPasteboard];
        if pb.is_null() {
            return Err(anyhow!("no general pasteboard"));
        }
        let _: i64 = msg_send![pb, clearContents];

        // Declare every type up front so the marker UTIs are registered
        // before any data lands on the pasteboard. Some clipboard managers
        // poll on changeCount and only re-read [pb types] once; if we add
        // marker types incrementally after setString, those managers can
        // miss them. declareTypes:owner: announces the full set atomically.
        let ns_text = NSString::from_str(text);
        let ns_type_string = NSString::from_str(NS_PASTEBOARD_TYPE_STRING);
        let ns_type_transient = NSString::from_str(NS_PASTEBOARD_TYPE_TRANSIENT);
        let ns_type_autogen = NSString::from_str(NS_PASTEBOARD_TYPE_AUTOGENERATED);
        let ns_type_concealed = NSString::from_str(NS_PASTEBOARD_TYPE_CONCEALED);
        let empty = NSString::from_str("");

        let mutable_array_cls = objc2::class!(NSMutableArray);
        let types_array: *mut AnyObject = msg_send![mutable_array_cls, arrayWithCapacity: 4usize];
        let _: () = msg_send![types_array, addObject: &*ns_type_string];
        let _: () = msg_send![types_array, addObject: &*ns_type_transient];
        let _: () = msg_send![types_array, addObject: &*ns_type_autogen];
        let _: () = msg_send![types_array, addObject: &*ns_type_concealed];
        let nil_owner: *mut AnyObject = std::ptr::null_mut();
        let _: i64 = msg_send![pb, declareTypes: types_array, owner: nil_owner];

        let ok: bool = msg_send![pb, setString: &*ns_text, forType: &*ns_type_string];
        if !ok {
            return Err(anyhow!("pasteboard setString failed"));
        }
        // Marker types: the value is ignored — managers only check whether
        // the type is present in [pb types].
        let _: bool = msg_send![pb, setString: &*empty, forType: &*ns_type_transient];
        let _: bool = msg_send![pb, setString: &*empty, forType: &*ns_type_autogen];
        let _: bool = msg_send![pb, setString: &*empty, forType: &*ns_type_concealed];
    }
    Ok(())
}

fn read_pasteboard() -> Option<String> {
    unsafe {
        let cls = objc2::class!(NSPasteboard);
        let pb: *mut AnyObject = msg_send![cls, generalPasteboard];
        if pb.is_null() {
            return None;
        }
        let ns_type = NSString::from_str(NS_PASTEBOARD_TYPE_STRING);
        let s: *mut AnyObject = msg_send![pb, stringForType: &*ns_type];
        if s.is_null() {
            return None;
        }
        let utf8: *const u8 = msg_send![s, UTF8String];
        if utf8.is_null() {
            return None;
        }
        Some(std::ffi::CStr::from_ptr(utf8 as *const _).to_string_lossy().into_owned())
    }
}

fn write_pasteboard_plain(text: &str) -> Result<()> {
    unsafe {
        let cls = objc2::class!(NSPasteboard);
        let pb: *mut AnyObject = msg_send![cls, generalPasteboard];
        if pb.is_null() {
            return Err(anyhow!("no general pasteboard"));
        }
        let _: i64 = msg_send![pb, clearContents];
        let ns_text = NSString::from_str(text);
        let ns_type = NSString::from_str(NS_PASTEBOARD_TYPE_STRING);
        let ok: bool = msg_send![pb, setString: &*ns_text, forType: &*ns_type];
        if !ok {
            return Err(anyhow!("pasteboard restore failed"));
        }
    }
    Ok(())
}

fn clear_pasteboard() -> Result<()> {
    unsafe {
        let cls = objc2::class!(NSPasteboard);
        let pb: *mut AnyObject = msg_send![cls, generalPasteboard];
        if pb.is_null() {
            return Err(anyhow!("no general pasteboard"));
        }
        let _: i64 = msg_send![pb, clearContents];
    }
    Ok(())
}

fn restore_focus(target: &FocusTarget) -> Result<()> {
    unsafe {
        let cls = objc2::class!(NSRunningApplication);
        let app: *mut AnyObject = msg_send![cls, runningApplicationWithProcessIdentifier: target.pid];
        if app.is_null() {
            return Err(anyhow!("target pid {} not running", target.pid));
        }
        let _: bool = msg_send![app, activateWithOptions: NS_APPLICATION_ACTIVATE_ALL_WINDOWS];
    }
    Ok(())
}

fn synthesize_cmd_v() -> Result<()> {
    let src = CGEventSource::new(CGEventSourceStateID::CombinedSessionState)
        .map_err(|_| anyhow!("CGEventSource::new failed"))?;
    let down = CGEvent::new_keyboard_event(src.clone(), KEY_V, true)
        .map_err(|_| anyhow!("keydown create failed"))?;
    down.set_flags(CGEventFlags::CGEventFlagCommand);
    down.post(CGEventTapLocation::HID);
    let up = CGEvent::new_keyboard_event(src, KEY_V, false)
        .map_err(|_| anyhow!("keyup create failed"))?;
    up.set_flags(CGEventFlags::CGEventFlagCommand);
    up.post(CGEventTapLocation::HID);
    Ok(())
}
